2021-07-06 22:16:31,051 - line 32 - interpret_signal - Exception occurred in title: 'signal'
Traceback (most recent call last):
  File "C:\python_step3\src\routes.py", line 26, in interpret_signal
    response = parser.get_signal_title(data['signal'])
KeyError: 'signal'
2021-07-06 22:21:25,257 - line 30 - interpret_signal - Exception occurred in title: 'signal'
Traceback (most recent call last):
  File "C:\python_step3\src\routes.py", line 26, in interpret_signal
    response = parser.get_signal_title(data['signal'])
KeyError: 'signal'
2021-07-06 22:30:05,456 - line 30 - interpret_signal - Exception occurred in title: 'signal'
Traceback (most recent call last):
  File "C:\python_step3\src\routes.py", line 26, in interpret_signal
    response = parser.get_signal_title(data['signal'])
KeyError: 'signal'
2021-07-06 22:30:19,506 - line 30 - interpret_signal - Exception occurred in title: 'signal'
Traceback (most recent call last):
  File "C:\python_step3\src\routes.py", line 26, in interpret_signal
    response = parser.get_signal_title(data['signal'])
KeyError: 'signal'
